---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: contents/00-introduction
  label: Introduction
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/30-administrator-guide
  label: 'Administrator Guide '
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/35-catalog-manager-guide
  label: Catalog Manager Guide
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/45-connected-apps
  label: Connected apps
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/70-integrate-with-nbold
  label: Integrate with nBold
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/80-open-source
  label: Open-source
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: contents/90-trust-center
  label: Trust Center
  create: all
  match: "**/*"
  templates:
  - article
upload_dir: static/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: node:18
  mount_path: "/build"
  working_dir: "/srv"
  instant_preview_command: npm run start
