---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: contents/00-introduction
  label: Introduction
  create: documents
  match: "**/*"
- type: directory
  path: contents/10-quickstart
  label: Quickstart
  create: documents
  match: "**/*"
- type: directory
  path: contents/30-administrator-guide
  label: 'Administrator Guide '
  create: documents
  match: "**/*"
- type: directory
  path: contents/40-collaboration-templates
  label: Collaboration templates
  create: documents
  match: "**/*"
- type: directory
  path: contents/60-business-scenarios
  label: Business scenarios
  create: documents
  match: "**/*"
- type: directory
  path: contents/45-connected-apps
  label: Connected apps
  create: documents
  match: "**/*"
- type: directory
  path: contents/50-governance-policies
  label: Governance policies
  create: documents
  match: "**/*"
- type: directory
  path: contents/70-automation
  label: Automation
  create: documents
  match: "**/*"
- type: directory
  path: contents/75-api
  label: API
  create: documents
  match: "**/*"
- type: directory
  path: contents/80-open-source
  label: Open-source
  create: documents
  match: "**/*"
- type: directory
  path: contents/90-trust-center
  label: Trust Center
  create: documents
  match: "**/*"
upload_dir: static/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
