name: Generate static assets, deploy to Azure Static Website and check for dead links in markdown files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install

      - name: Build with VuePress
        run: |
          npm run build

      - name: Deploy to Azure Static Website
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MEADOW_096585F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist"
          skip_app_build: true
          output_location: ""

      - name: Check all links in markdown files
        id: check_markdown_links
        run: |
          npm run test

      - name: "Read markdown-link-check log file"
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "./build/makdown_links_check/links_check.log"

      - name: Create report issue from log file
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "guillaumemeyer"
          labels: "links_check"
          title: "Markdown Links Report"
          body: ${{ steps.read_file.outputs.contents }}
          pinned: true
          close-previous: true
          linked-comments: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
