name: Generate static assets and deploy to Azure Static Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Build static assets
        run: |
          npm run build

      - name: Deploy to Azure Static Website
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MEADOW_096585F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist"
          skip_app_build: true
          output_location: ""

  # Call the links check workflow
  call-links-check:
    needs: build_deploy
    uses: ./.github/workflows/links-check.yml