name: Generate docs website and deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-publish-assets:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install

      - name: Generate assets
        run: |
          bun run build

      # See: https://github.com/marketplace/actions/git-commit-push-action
      - name: Publish assets
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: Updated public assets
          target_branch: published
          force: true
