name: Check for dead links in published website

on:
  workflow_dispatch:
  workflow_call:

jobs:
  links_check:
    name: Check links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install

      - name: Check all links
        id: check_website_links
        run: |
          npm run test

      - name: "Read check log file"
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "./build/website_links_check/links_check.log"

      - name: Create report issue from log file
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "guillaumemeyer"
          labels: "links_check"
          title: "Markdown Links Report"
          body: ${{ steps.read_file.outputs.contents }}
          pinned: true
          close-previous: true
          linked-comments: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
